# Classes
module ErogeImeDic
  module Util
    def to_katakana: -> untyped
    def to_hiragana: -> untyped
  end

  module ErogameScape
    def self.query: (String sql) -> Array[Hash[String,String]]
    def self.fetch_all_paginate: (?interval: Integer) { (nil|Hash[String,String]) -> String } -> Array[untyped]
    def self.characters: -> Array[untyped]
    def self.brands: -> Array[untyped]
    def self.musics: -> Array[untyped]
    def self.games: -> Array[untyped]
  end

  class DictionaryBuilder
    attr_accessor data: Array[Array[untyped]]
    attr_accessor header_comment: String
    def initialize: (?data: Array[Array[untyped]], ?header_comment: String) -> void
    def generate_mozc: (IO io) -> void

    private
    def escape_skk: (String str, ?escape: :concat) -> String

    public
    def generate_skk: (IO io) -> void
  end

  module DictionarySource
    CACHE_DIRECTORY: String

    def self.restore_cache: (String path) { -> untyped } -> untyped
    def self.normalize_text: (String text) -> String
    def self.neologd_path: -> String
    def self.split_yomi: (Array[[String, String]]) -> Array[[String, String]]
    def self.characters: -> Array[[String, String]]
    def self.brands: -> Array[[String, String]]
    def self.musics: -> Array[[String, String]]
    def self.games: (?include_nuki: bool, ?include_doujin: bool) -> Array[[String, String]]

    class Modification
      @deletions: Array[Hash[Symbol, String]]
      @additions: Array[[String, String]]
      @splits: Array[Hash[Symbol, String]]
      @ignore_parenthesis: Array[Hash[Symbol, String]]
      @original_data: Array[Hash[String, String]]
      @transform: ^(untyped) -> [untyped, untyped]

      def initialize: (Array[Hash[String, String]] original_data) { (untyped) -> [untyped, untyped] } -> void
      def add: (String furigana, String name) -> void
      def del: (?Integer? id, ?String? name, **String) -> void
      def spl: (?Integer? id, ?String? name, **String) -> void
      def ign: (?Integer? id, ?String? name, **String) -> void
      def run: { (Modification) -> void } -> Array[[String, String]]
    end
  end
end
